version: "3.9"

services:
  db:
    image: postgres:15
    container_name: futbic_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: futbic_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
    restart: on-failure

volumes:
  pgdata: